alter table public.user_preferences enable row level security;
alter table public.habits_log enable row level security;
alter table public.weekly_targets enable row level security;
alter table public.goals enable row level security;
alter table public.estate_flags enable row level security;
alter table public.ventures enable row level security;
alter table public.tasks enable row level security;
alter table public.routines enable row level security;
alter table public.focus_sessions enable row level security;
alter table public.metrics enable row level security;
alter table public.vision_board enable row level security;
alter table public.designs enable row level security;
alter table public.content_analytics enable row level security;
alter table public.agent_logs enable row level security;

drop policy if exists owner_only_user_preferences on public.user_preferences;
create policy owner_only_user_preferences on public.user_preferences for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);
drop policy if exists owner_only_habits_log on public.habits_log;
create policy owner_only_habits_log on public.habits_log for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);
drop policy if exists owner_only_weekly_targets on public.weekly_targets;
create policy owner_only_weekly_targets on public.weekly_targets for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);
drop policy if exists owner_only_goals on public.goals;
create policy owner_only_goals on public.goals for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);
drop policy if exists owner_only_estate_flags on public.estate_flags;
create policy owner_only_estate_flags on public.estate_flags for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);
drop policy if exists owner_only_ventures on public.ventures;
create policy owner_only_ventures on public.ventures for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);
drop policy if exists owner_only_tasks on public.tasks;
create policy owner_only_tasks on public.tasks for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);
drop policy if exists owner_only_routines on public.routines;
create policy owner_only_routines on public.routines for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);
drop policy if exists owner_only_focus_sessions on public.focus_sessions;
create policy owner_only_focus_sessions on public.focus_sessions for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);
drop policy if exists owner_only_metrics on public.metrics;
create policy owner_only_metrics on public.metrics for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);
drop policy if exists owner_only_vision_board on public.vision_board;
create policy owner_only_vision_board on public.vision_board for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);
drop policy if exists owner_only_designs on public.designs;
create policy owner_only_designs on public.designs for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);
drop policy if exists owner_only_content_analytics on public.content_analytics;
create policy owner_only_content_analytics on public.content_analytics for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);
drop policy if exists owner_only_agent_logs on public.agent_logs;
create policy owner_only_agent_logs on public.agent_logs for all using (auth.uid() = owner_uid) with check (auth.uid() = owner_uid);

